version: '3'

networks:
  ansible:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.61.0/24

services:
  ansible:
      build: .
      ports:
        - "32751:22"
      networks:
        ansible:
          ipv4_address: 192.168.61.2
      dns: 8.8.8.8
      domainname: ansible.castic
      hostname: centos_one
      restart: always