version: "3"

services: 
  jenkins:
    hostname: jenkins-linux
    image:  jenkinsci/blueocean
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    environment: 
      - "JAVA_OPTS=-Xms256m -Xmx512m"
    volumes:
    - jenkins-data:/var/jenkins_home
    # This mapping allows the jenkinsci/blueocean 
    # container to communicate with the Docker daemon
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
    driver: local
