version: "3"

services:
  mongo:
    image: "mongo:3-stretch"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_LOG_DIR=/var/log/mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: "mongo-express:latest"
    hostname:  mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=piggy.ad.fiu.edu
      - ME_CONFIG_MONGODB_PORT=27017
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - mongo-express_data:/data/db
  
volumes:
  mongo_data:
    driver: local
  mongo-express_data:
    driver: local